name: 西土城伍伍慧
description: Computer Vision and Music make the world a better place
meta_description: ""

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: ''
google_analytics: ''
gems: [jekyll-paginate]
future: true

# Details for the RSS feed generator
url:            'blog url'
author:         'Squids Zyd'
